import streamlit as st
import plotly.express as px

from utils.ratios import compute_ratios, variance_analysis, highlight_variance, flag_risks
from utils.scoring import compute_health_score, score_label
from utils.claude_client import generate_summary
from utils.report_generator import generate_report
from utils.session_limit import get_api_key, check_and_consume_quota

st.set_page_config(page_title="Dashboard | FinSight AI", page_icon="\U0001F4CA", layout="wide")
st.title("Dashboard")

if "extracted_data" not in st.session_state:
    st.warning("No data loaded yet -- go to the main page and choose a data source.")
    st.stop()

data = st.session_state["extracted_data"]
periods = data.get("periods", [])
ratios_df = compute_ratios(data)
variance_df = variance_analysis(data)
variance_highlights = highlight_variance(variance_df)
risk_flags = flag_risks(ratios_df, variance_df)
health = compute_health_score(data, ratios_df)

st.subheader(data.get("company_name", "Company"))
st.caption(data.get("currency_or_units", ""))

# ---- Financial Health Score ----
st.markdown("## Financial Health")
score_cols = st.columns([1, 3])
with score_cols[0]:
    overall = health["overall"]
    st.metric("Overall Score", f"{overall}/100" if overall is not None else "N/A",
               help="Rule-based score from Liquidity, Leverage, Asset Growth, and Equity Strength. "
                    "Not generated by AI.")
    st.markdown(f"### {score_label(overall)}")
with score_cols[1]:
    cat_cols = st.columns(len(health["categories"]))
    for col, (cat, info) in zip(cat_cols, health["categories"].items()):
        with col:
            s = info["score"]
            st.metric(cat, f"{s}/100" if s is not None else "N/A")
            st.caption(info["detail"])

st.divider()

# ---- Key metrics (latest period) ----
if periods:
    latest = periods[-1]
    cols = st.columns(4)
    revenue = data.get("income_statement", {}).get("revenue", {}).get(latest)
    net_income = data.get("income_statement", {}).get("net_income", {}).get(latest)
    net_margin = ratios_df.loc["Net Margin %", latest] if "Net Margin %" in ratios_df.index else None
    current_ratio = ratios_df.loc["Current Ratio", latest] if "Current Ratio" in ratios_df.index else None

    cols[0].metric("Revenue", f"{revenue:,.0f}" if revenue is not None else "N/A")
    cols[1].metric("Net Income", f"{net_income:,.0f}" if net_income is not None else "N/A")
    cols[2].metric("Net Margin", f"{net_margin}%" if net_margin is not None else "N/A")
    cols[3].metric("Current Ratio", f"{current_ratio}" if current_ratio is not None else "N/A")

st.divider()

# ---- Ratio table ----
st.subheader("Ratios by period")
st.dataframe(ratios_df, use_container_width=True)

st.divider()

# ---- Trend charts ----
st.subheader("Trends")
chart_cols = st.columns(2)

with chart_cols[0]:
    inc = data.get("income_statement", {})
    if periods and "revenue" in inc:
        fig = px.line(x=periods, y=[inc["revenue"].get(p) for p in periods],
                       markers=True, title="Revenue by period",
                       labels={"x": "Period", "y": "Revenue"})
        st.plotly_chart(fig, use_container_width=True)

with chart_cols[1]:
    margin_rows = [r for r in ["Gross Margin %", "Operating Margin %", "Net Margin %"]
                   if r in ratios_df.index]
    if margin_rows:
        margin_df = ratios_df.loc[margin_rows].T.reset_index().rename(columns={"index": "Period"})
        fig2 = px.line(margin_df, x="Period", y=margin_rows, markers=True,
                        title="Margin trends (%)")
        st.plotly_chart(fig2, use_container_width=True)

chart_cols2 = st.columns(2)
with chart_cols2[0]:
    bs = data.get("balance_sheet", {})
    if periods and "total_assets" in bs and "total_liabilities" in bs:
        fig3 = px.line(x=periods,
                        y=[bs["total_assets"].get(p) for p in periods],
                        markers=True, title="Total Assets by period",
                        labels={"x": "Period", "y": "Total Assets"})
        st.plotly_chart(fig3, use_container_width=True)

with chart_cols2[1]:
    if "Working Capital" in ratios_df.index:
        wc_df = ratios_df.loc[["Working Capital"]].T.reset_index().rename(columns={"index": "Period"})
        fig4 = px.bar(wc_df, x="Period", y="Working Capital", title="Working Capital trend")
        st.plotly_chart(fig4, use_container_width=True)

st.divider()

# ---- Variance Analysis ----
st.subheader("Variance Analysis (YoY % change)")
st.dataframe(variance_df, use_container_width=True)
if variance_highlights:
    for h in variance_highlights:
        st.info(h)

st.divider()

# ---- Risk flags ----
st.subheader("Risk Assessment")
if risk_flags:
    for label, detail in risk_flags:
        st.warning(f"**{label}** -- {detail}")
else:
    st.success("No rule-based risk flags triggered on the latest period.")

st.divider()

# ---- AI narrative summary ----
st.subheader("AI Insights")
st.caption("Claude explains the numbers above -- it does not calculate them.")
_api_key, _ = get_api_key()
if _api_key:
    if st.button("Generate AI insights"):
        if check_and_consume_quota():
            with st.spinner("Writing insights with Claude..."):
                try:
                    summary = generate_summary(
                        _api_key, data, ratios_df.to_dict(),
                        health_score=health, risk_flags=risk_flags,
                        variance_highlights=variance_highlights,
                    )
                    st.session_state["summary"] = summary
                except Exception as e:
                    st.error(f"Couldn't generate AI insights: {e}")
    if "summary" in st.session_state:
        st.markdown(st.session_state["summary"])
else:
    st.caption("Add an Anthropic API key on the main page to generate AI insights.")

st.divider()

# ---- Downloadable report ----
st.subheader("Download Report")
report_bytes = generate_report(
    extracted_data=data,
    ratios_df=ratios_df,
    health_score=health,
    risk_flags=risk_flags,
    variance_highlights=variance_highlights,
    ai_summary=st.session_state.get("summary"),
    validation=st.session_state.get("validation_result"),
)
st.download_button(
    "\U0001F4E5 Download Financial Analysis Report (PDF)",
    data=report_bytes,
    file_name=f"{data.get('company_name', 'financial_report').replace(' ', '_')}_report.pdf",
    mime="application/pdf",
)
